#!/bin/sh

set -e

npx eslint .

npx stylelint "**/*.css" --allow-empty-input

STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.js$' || true)

if [ -n "$STAGED_JS_FILES" ]; then
  node --experimental-vm-modules node_modules/jest/bin/jest.js --bail --findRelatedTests $STAGED_JS_FILES
else
  npm test
fi
